version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-inventory-db
    environment:
      POSTGRES_DB: inventory_db       # Matches your database name
      POSTGRES_USER: admin             # Username from your config
      POSTGRES_PASSWORD: newp      # Password from your config
    ports:
      - "5432:5432" 
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - inventory-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - inventory-network

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    ports:
      - "9092:9092"
      - "9093:9093"  # Add this if using port 9093 for the INSIDE listener
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # Define listeners (INSIDE and OUTSIDE)
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      # Map security protocols for each listener
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      # Advertised listeners for internal/external connections
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    depends_on:
      - zookeeper
    networks:
      - inventory-network

volumes:
  postgres-data:

networks:
  inventory-network:
    driver: bridge